-- AlterTable
ALTER TABLE "public"."estudiantes" ALTER COLUMN "nombre" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "apellido" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "cedula" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "fecha_nacimiento" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "ciudad" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "telefono" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "public"."materias" ALTER COLUMN "nombre" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "codigo" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "public"."usuarios" ALTER COLUMN "nombre" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "apellido" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(50);
